name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.x]
    name: Go $${{matrix.go}}v
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with: 
          go-version: ${{matrix.go}}
      - name: Run Tests
        run: make test
